CREATE DATABASE bdd_mon_site_ecomm DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE ARTICLES (
ID_ARTICLE char(5) NOT NULL, 
LIBELLE char(20) DEFAULT NULL, 
PVTTC decimal(9,2) DEFAULT NULL, 
DESCRIPTION char(120) DEFAULT NULL, 
VISUEL char(30) DEFAULT NULL, 
PRIMARY KEY (ID_ARTICLE)
)


CREATE TABLE CLIENT (
NUM_CLIENT int DEFAULT NULL, 
NOM char(30) DEFAULT NULL,
PRENOM char(30) DEFAULT NULL, 
ADR_MAIL char(60) DEFAULT NULL, 
DATE_NAISSANCE date DEFAULT NULL, 
ADR_POSTALE char(120) DEFAULT NULL, 
PRIMARY KEY (NUM_CLIENT)
)


CREATE TABLE COMMANDE (
ID_COMMANDE int NOT NULL, 
NUM_CLIENT int DEFAULT NULL, 
DATE_COMMANDE date DEFAULT NULL, 
TOTAL decimal(9,2) DEFAULT NULL,
PRIMARY KEY (ID_COMMANDE), 
CONSTRAINT FK_TICKET_FK1 FOREIGN KEY (NUM_CLIENT) REFERENCES CLIENT (NUM_CLIENT)
)

CREATE TABLE LIGNES_COMMANDE (
ID_COMMANDE int NOT NULL,
NUM_LIGNE int NOT NULL, 
ID_ARTICLE char(5) DEFAULT NULL, 
QTE int DEFAULT NULL,
PVU decimal(9,2) DEFAULT NULL,
PRIMARY KEY (ID_COMMANDE,NUM_LIGNE),
CONSTRAINT FK_LIGNES_COMMANDE_FK1 FOREIGN KEY (ID_COMMANDE) REFERENCES COMMANDE (ID_COMMANDE),
CONSTRAINT FK_LIGNES_COMMANDE_FK3 FOREIGN KEY (ID_ARTICLE) REFERENCES ARTICLES (ID_ARTICLE)
);